FROM mysql:8.0

# Set the MySQL root password (change it to a secure password)
ENV MYSQL_ROOT_PASSWORD=password

# Create a new database (change 'laravel_db' to your desired database name)
ENV MYSQL_DATABASE=db

# Expose port 3306
EXPOSE 3306
